apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-2
  annotations:
    kubernetes.io/change-cause: "Changed node port to 9100"
spec:
  replicas: 4
  selector:
    matchLabels:
      app: test-app
  template:
    #Dichiarazione POD
    metadata:
      labels:
        app: test-app #Deve matchare il matchLabels
    spec:
      #Dichiarazioni specifiche container
      containers:
      - name: nginx-container
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      - name: node-container
        image: prom/node-exporter
        ports:
        - containerPort: 9100





# Deploy di 4 Pod con all'interno ciascuno due container nginx